name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        proj: [Monitoring.Test, Monitoring.Web.Test]

    defaults:
      run:
        working-directory: ./src

    name: Running Tests - ${{ matrix.proj }}
    env:
        PACKAGE_PROJECT_DIR: DR.Common.${{ matrix.proj }}
        PACKAGE_PROJECT_NAME: DR.Common.${{ matrix.proj }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/drdk/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Build test project and run tests
        if: env.PACKAGE_PROJECT_NAME != ''
        run: |
          dotnet test './${{ env.PACKAGE_PROJECT_NAME }}/${{ env.PACKAGE_PROJECT_NAME }}.csproj'
